
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LOVE 4 GALLI', 'blanco', 'Esta es perfecta para rockearla en tal fecha, un uniforme para todo cuaadeño o artista de closet', '270', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443976/productos_LucaSantorini/playera_luca_love_for_galli.jpg', 'https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553321/LOVE_4_GALLI_FRONTAL_BLANCA_cjtkic.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LSSW x DANNY OCÉANO Babylon G', 'rojo', 'En más de 5 colorways', '300', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443974/productos_LucaSantorini/playera_dannyocean_babylon_roja.jpg', 'https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553305/LSSW_x_DANNY_OC%C3%89ANO_BABYLON_G_ROJA_DELANTERA_pgaphf.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LSSW x DANNY OCÉANO Babylon G', 'verde', 'En más de 5 colorways', '300', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443974/productos_LucaSantorini/playera_dannyocean_babylon_verde.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553314/LSSW_x_DANNY_OC%C3%89ANO_BABYLON_G_VERDE_DELANTERA_vjxzlg.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LSSW x DANNY OCÉANO Babylon G', 'azul', 'En más de 5 colorways', '300', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443972/productos_LucaSantorini/playera_dannyocean_babylon_azulrey.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553321/LSSW_x_DANNY_OCEAN_BABYLON_G_AZUL_MARINO_FRONTAL_jqkuie.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LSSW x DANNY OCÉANO Babylon G', 'azul navy', 'En más de 5 colorways', '300', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443973/productos_LucaSantorini/playera_dannyocean_babylon_azulmarino.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553319/LSSW_x_DANNY_OC%C3%89ANO_BABYLON_G_AZUL_REY_FRONTAL_jnkkfc.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LSSW x DANNY OCÉANO Babylon G', 'cafe', 'En más de 5 colorways', '300', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443972/productos_LucaSantorini/playera_dannyocean_babylon_cafe.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1678169034/LSSW_x_DANNY_OCEAN_BABYLON_G_NEGRA_FRONTAL_agbqxl.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('HARRY EN GUANATOS', 'blanco', 'It was given to me on my last visit to the VFG Arena… ', '300', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443976/productos_LucaSantorini/playera_harry_en_guanatos02_blanca.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553304/HARRY_EN_GUANATOS_BLANCA_FRONTAL_hvt0jz.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LAS DEL BELLAKEO', 'beige', '¿Sabias que Daddy Yankee fue maestro en la facultad del perreo en PR? ', '350', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443972/productos_LucaSantorini/playera_bellakeo_beige.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553302/LAS_DEL_BELLAKEO_BEIGE_FRONTAL_lsgtsu.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LAS DEL BELLAKEO', 'azul', '¿Sabias que Daddy Yankee fue maestro en la facultad del perro en PR?', '350', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443972/productos_LucaSantorini/playera_bellakeo_azul_rey.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553300/LAS_DEL_BELLAKEO_AZUL_FRONTAL_so3nr3.png');
INSERT INTO `productos` ( `nombre`, `color`, `descripcion`, `precio`, `foto`, `fotop`) VALUES ('LAS DEL BELLAKEO', 'azul navy', '¿Sabias que Daddy Yankee fue maestro en la facultad del perro en PR? ', '350', 'https://res.cloudinary.com/dgp2sgznp/image/upload/v1677443972/productos_LucaSantorini/playera_bellakeo_azulmarino.jpg','https://res.cloudinary.com/dzrqrtezc/image/upload/v1677553319/LAS_DEL_BELLAKEO_NEGRA_FRONTAL_rhoyyl.png');

INSERT INTO `pedidos` ( `monto_total`, `metodo_pago`, `fecha_solicitud`, `fk_id_usuario`) VALUES ( '270', 'tarjeta', '2022-12-23','1');
INSERT INTO `pedidos` ( `monto_total`, `metodo_pago`, `fecha_solicitud`, `fk_id_usuario`) VALUES ( '600', 'tarjeta', '2023-01-12','2');
INSERT INTO `pedidos` ( `monto_total`, `metodo_pago`, `fecha_solicitud`, `fk_id_usuario`) VALUES ( '570', 'tarjeta', '2023-02-24', '3');
INSERT INTO `pedidos` ( `monto_total`, `metodo_pago`, `fecha_solicitud`, `fk_id_usuario`) VALUES ( '350', 'tarjeta', '2023-02-25','4');

INSERT INTO `pedidos_has_productos` ( `cantidad`, `subtotal`, `detalles`, `fk_id_pedido`, `fk_id_producto`) VALUES ('1', '270', 'pedido completado exitosamente', '1', '1');
INSERT INTO `pedidos_has_productos` ( `cantidad`, `subtotal`, `detalles`, `fk_id_pedido`, `fk_id_producto`) VALUES ('1', '300', 'pedido completado exitosamente', '2', '4');
INSERT INTO `pedidos_has_productos` ( `cantidad`, `subtotal`, `detalles`, `fk_id_pedido`, `fk_id_producto`) VALUES ('1', '300', 'pedido completado exitosamente', '2', '19');
INSERT INTO `pedidos_has_productos` ( `cantidad`, `subtotal`, `detalles`, `fk_id_pedido`, `fk_id_producto`) VALUES ('1', '270', 'pedido completado exitosamente', '3', '1');
INSERT INTO `pedidos_has_productos` ( `cantidad`, `subtotal`, `detalles`, `fk_id_pedido`, `fk_id_producto`) VALUES ('1', '300', 'pedido completado exitosamente', '3', '5');
INSERT INTO `pedidos_has_productos` ( `cantidad`, `subtotal`, `detalles`, `fk_id_pedido`, `fk_id_producto`) VALUES ('1', '350', 'pedido completado exitosamente', '4', '30');
